"use strict";

const fs = require("node:fs");
const path = require("node:path");

const output = path.join(__dirname, "..", "js", "config.runtime.js");
const envFile = path.join(__dirname, "..", ".env");

function readDotEnv() {
  if (!fs.existsSync(envFile)) return {};
  return fs.readFileSync(envFile, "utf8").split(/\r?\n/).reduce((result, line) => {
    const match = line.match(/^\s*([A-Z][A-Z0-9_]*)\s*=\s*(.*?)\s*$/);
    if (match && !match[1].startsWith("#")) result[match[1]] = match[2].replace(/^['"]|['"]$/g, "");
    return result;
  }, {});
}

const dotEnv = readDotEnv();
function env(name) {
  return process.env[name] || dotEnv[name] || "";
}

const values = {
  supabaseUrl: env("PHANTOM_SUPABASE_URL"),
  anonKey: env("PHANTOM_SUPABASE_ANON_KEY"),
  apiBase: env("PHANTOM_API_BASE"),
  pollIntervalMs: Number(env("PHANTOM_POLL_INTERVAL_MS") || 0),
  requestTimeoutMs: Number(env("PHANTOM_REQUEST_TIMEOUT_MS") || 0)
};

// Build-log diagnostics: report whether each build-time variable reached the
// build process. Values are masked, never printed in full.
function describe(value) {
  if (!value) return "MISSING";
  if (value.length <= 10) return "set (" + value.length + " chars)";
  return "set (" + value.length + " chars: " + value.slice(0, 6) + "..." + value.slice(-4) + ")";
}
console.log("[config] PHANTOM_SUPABASE_URL      = " + describe(values.supabaseUrl));
console.log("[config] PHANTOM_SUPABASE_ANON_KEY = " + describe(values.anonKey));
console.log("[config] PHANTOM_API_BASE          = " + describe(values.apiBase));
console.log("[config] PHANTOM_POLL_INTERVAL_MS  = " + (values.pollIntervalMs || "MISSING"));
console.log("[config] PHANTOM_REQUEST_TIMEOUT_MS= " + (values.requestTimeoutMs || "MISSING"));

function jsString(value) {
  return JSON.stringify(value);
}

const content = `/* Generated by scripts/generate-config.js. Do not edit or commit. */
(function (root) {
  "use strict";
  var config = root.APP_CONFIG;
  if (${jsString(values.supabaseUrl)}) config.SUPABASE_URL = ${jsString(values.supabaseUrl)};
  if (${jsString(values.anonKey)}) config.ANON_KEY = ${jsString(values.anonKey)};
  if (${jsString(values.apiBase)}) config.API_BASE = ${jsString(values.apiBase)};
  if (${values.pollIntervalMs > 0}) config.GAME.pollIntervalMs = ${values.pollIntervalMs};
  if (${values.requestTimeoutMs > 0}) config.GAME.requestTimeoutMs = ${values.requestTimeoutMs};
}(window));
`;

fs.writeFileSync(output, content, "utf8");
console.log("Generated " + path.relative(process.cwd(), output));
